version: '3.7'
services:
  vcn:
    image: golang:1.12-stretch
    entrypoint: "sh -c 'mkdir -p /go/bin && cd /app/vcn && go clean && go get -v && go build -v && go test -v'"
    environment:
      GOPATH: /go
      GOBIN: /go/bin
    volumes: 
      - "./:/app"
      - "gosrc:/go/src"
volumes:
  gosrc:
