version: '3.7'
services:
  vcn:
    image: golang:1.12-stretch
    entrypoint: "sh -c 'cp -R /src/* /build && cd /build && go mod vendor && go build -v ./cmd/vcn && go test -v ./...'"
    environment:
      LOG_LEVEL: "TRACE"
    volumes:
      - "./:/src"
      - "build:/build"
      - "gopkg:/go/pkg"
volumes: 
  build:
  gopkg: